language: php

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2

env:
  - SYMFONY_VERSION="4.1.*" DB=mysql

before-install:
  - composer self-update

install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console make:migration --env=test
  - php bin/console doctrine:migrations:migrate --env=test

script:
  - phpunit

notifications:
  email: martinkondor@gmail.com