language: php
php: 
  - '7.2'
sudo: false
services:
  - mysql
  
cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true

env:
  - SYMFONY_VERSION="4.1.*" DB=mysql

before-install:
  - composer self-update

install:
  - composer install

script:
  - phpunit

notifications:
  email: martinkondor@gmail.com